version: "3.9"
services:
  app:
    build: .
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=mysql://root:${MARIADB_ROOT_PASSWORD}@mariadb:3306/oncall
      - PORT=5000
    ports:
      - 5001:5000
    networks:
      - db-network
  db:
    image: mariadb:latest
    restart: always
    env_file: .env
    healthcheck:
      test: mariadb ${MARIADB_DATABASE} --user=${MARIADB_USER} --password='${MARIADB_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      db-network:
        aliases:
          - mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    

networks:
  db-network:

volumes:
  mariadb-data:

