# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ivy-oncall

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_77307e59a2c14bfcb795e9ea58c18b77 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ca874249e1b446a89e6c12add88c589c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_77307e59a2c14bfcb795e9ea58c18b77 }}/ivysaur-unb/on-call-coordinator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ivy-oncall'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1e23433a2d914730bf0ea0c5c3b2a25f }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_77307e59a2c14bfcb795e9ea58c18b77 }}/ivysaur-unb/on-call-coordinator:${{ github.sha }}'